version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install build dependencies
          command: |
            npm install
            sudo apt-get install awscli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run:
          name: Build site assets
          command: |
            yarn release  
      
      - deploy:
          name: Deploy to S3/Cloudfront
          command: |
            echo "{ \"Paths\": { \"Quantity\": 1 , \"Items\": [\"/*\"] }, \"CallerReference\": \"circleci-$(date +%s)\" }" >> batch.json
            aws configure set preview.cloudfront true

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync out s3://www.aqinary.com --delete --cache-control max-age=1209600
              #aws cloudfront create-invalidation --distribution-id ENQXY6FBO2FIG --invalidation-batch file://batch.json
            fi